// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFC9JjqxmPrt-dqoglteRQC8o98-GcVTI',
    appId: '1:738437907221:android:fb5e3530d3f953c3d51f1c',
    messagingSenderId: '738437907221',
    projectId: 'amitomnitriage',
    storageBucket: 'amitomnitriage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoOLMWvsfgrzBdGdR9sSPhukPyBztJH8',
    appId: '1:738437907221:ios:ff2803f23e03d9f7d51f1c',
    messagingSenderId: '738437907221',
    projectId: 'amitomnitriage',
    storageBucket: 'amitomnitriage.firebasestorage.app',
    iosBundleId: 'com.example.omnitriageDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNoOLMWvsfgrzBdGdR9sSPhukPyBztJH8',
    appId: '1:738437907221:ios:ff2803f23e03d9f7d51f1c',
    messagingSenderId: '738437907221',
    projectId: 'amitomnitriage',
    storageBucket: 'amitomnitriage.firebasestorage.app',
    iosBundleId: 'com.example.omnitriageDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcwLSPCtjm7CYXSPiR3Z_Th20UYZz9fEE',
    appId: '1:738437907221:web:e6f18cd04e1d8e67d51f1c',
    messagingSenderId: '738437907221',
    projectId: 'amitomnitriage',
    authDomain: 'amitomnitriage.firebaseapp.com',
    storageBucket: 'amitomnitriage.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcwLSPCtjm7CYXSPiR3Z_Th20UYZz9fEE',
    appId: '1:738437907221:web:88baa91c7d517640d51f1c',
    messagingSenderId: '738437907221',
    projectId: 'amitomnitriage',
    authDomain: 'amitomnitriage.firebaseapp.com',
    storageBucket: 'amitomnitriage.firebasestorage.app',
  );
}
